login.head = Welcome to NeboTools
login.description = Please sign-in to your account and start to use the application

login.mailLabel = EMAIL OR USERNAME
login.mailInput = Enter your mail or username

login.passwordLabel = PASSWORD
login.passwordInput = Enter your password

login.remember = Remember Me

login.signIn = Sign In

twoStep.head = Two Step Verification 
twoStep.description = We sent a verification code to your mobile. Enter the code from the mobile in the field below. 
twoStep.digit = Type your 6 digit security code
twoStep.account = Verify my account

state.add = Add
state.detail = Détail
state.manage = Manage
state.modify = Modify
state.more = More
state.overview = Overview
state.none = None



product.entity = Product