login.head = Welcome to NeboTools
login.description = Please sign-in to your account and start to use the application

login.mailLabel = EMAIL OR USERNAME
login.mailInput = Enter your mail or username

login.passwordLabel = PASSWORD
login.passwordInput = Enter your password

login.remember = Remember Me

login.signIn = Sign In

twoStep.head = Two Step Verification 
twoStep.description = Enter your secret code 
twoStep.digit = Type your 6 digit security code
twoStep.account = Verify my account

state.add = Add
state.detail = Détail
state.manage = Manage
state.modify = Modify
state.more = More
state.overview = Overview
state.none = None

product.entity = PRODUCT
product.titleAdd = Add a new Product
product.titleSubAdd = Orders placed across your store
product.information = Product Informations
product.name = NAME
product.nameTitle = TITLE PRODUCT
product.barcode = BARCODE
product.description = DESCRIPTION (OPTIONAL)
product.quantity = QUANTITY
product.variant = VARIANT
product.expDate = EXPIRATION DATE
product.devDate = DELIVERY DATE
product.supplier = SUPPLIER
product.price = PRICE
product.status = STATUS
product.pricing = PRICING
product.basePrice = BASE PRICE
product.minPrice = MINIMUM PRICE
product.category = CATEGORY
product.add = Add Product
product.brand = BRAND
product.minimum = MINIMUM QTY


category.add = Add Category


employee.entity = EMPLOYEE
employee.titleAdd = Add a new Employee
employee.titleSubAdd = Employee can be connect to the app
employee.part1 = 1. #Account Detail
employee.part2 = 2. #Personal Informations
employee.login = LOGIN
employee.firstname = FIRST NAME
employee.lastname = LAST NAME
employee.password =	PASSWORD
employee.passwordVerify =	VERIFY PASSWORD
employee.mail =	MAIL
employee.phone = PHONE
employee.birth = BIRTH DATE
employee.sex = SEX
employee.add = Add Employee
employee.old = OLD


customer.entity = CUSTOMER
customer.titleAdd = Add a new Customer
customer.titleSubAdd = Customer can not be connect to the app
customer.part = #Personal Informations
customer.firstname = FIRST NAME
customer.lastname = LAST NAME
customer.phone = PHONE
customer.mail = MAIL
customer.payment = PAYMENT
customer.add = Add Customer



supplier.entity = SUPPLIER
supplier.titleAdd = Add a new Supplier
supplier.titleSubAdd = Supplier can not be connect to the app
supplier.part = #Personal Informations
supplier.firstname = FIRST NAME
supplier.lastname = LAST NAME
supplier.phone = PHONE
supplier.mail = MAIL
supplier.description = DESCRIPTION
supplier.payment = PAYMENT
supplier.add = Add Supplier


invoice.entity = INVOICE
invoice.titleAdd = Add a new Invoice
invoice.titleSubAdd = Invoice can not be updated
invoice.search = Search
invoice.item = Item
invoice.cost = Cost
invoice.quantity = Quantity
invoice.price = Price
invoice.add = Add Invoice


log.entity = LOG
log.type = Add a new Invoice
log.entityName = ENTITY
log.entityId = ENTITY ID


lot.add = Add another Lot
lot.inStock = In Stock
lot.addStock = Add Stock


btn.discard = Discard
btn.remove = Remove
btn.add = Add
btn.archive = Archive
btn.save = Save
titleAdd=Create property