login.head = Bienvenu chez NeboTools
login.description = Veuillez vous connecter pour commencer a utiliser l'application

login.mailLabel = MAIL OU NOM D'UTILISATEUR
login.mailInput = Entrer votre mail ou nom d'utilisateur

login.passwordLabel = MOT DE PASSE
login.passwordInput = Entrer votre mot de passe

login.remember = Se rappeler de Moi

login.signIn = Se Connecter




state.add = Ajout
state.detail = Détail
state.manage = Gestion
state.modify = Modification
state.more = Plus
state.overview = Vue d'ensemble
state.none = Aucun



product.entity = Produit