login.head = Bienvenu chez NeboTools
login.description = Veuillez vous connecter pour commencer a utiliser l'application

login.mailLabel = MAIL OU NOM D'UTILISATEUR
login.mailInput = Entrer votre mail ou nom d'utilisateur

login.passwordLabel = MOT DE PASSE
login.passwordInput = Entrer votre mot de passe

login.remember = Se rappeler de Moi

login.signIn = Se Connecter

twoStep.head = Vérification en deux étapes 
twoStep.description = Entrer votre code secret
twoStep.digit = Taper votre code à 6 chiffres
twoStep.account = Verifier mon compte

state.add = Ajout
state.detail = Détail
state.manage = Gestion
state.modify = Modification
state.more = Plus
state.overview = Vue d'ensemble
state.none = Aucun

product.entity = Produit
product.titleAdd = Ajouter un nouveau produit
product.titleSubAdd = Les commandes sont placé dans votre magasin