login.head = Bienvenu chez NeboTools
login.description = Veuillez vous connecter pour commencer a utiliser l'application

login.mailLabel = MAIL OU NOM D'UTILISATEUR
login.mailInput = Entrer votre mail ou nom d'utilisateur

login.passwordLabel = MOT DE PASSE
login.passwordInput = Entrer votre mot de passe

login.remember = Se rappeler de Moi

login.signIn = Se Connecter

twoStep.head = Vérification en deux étapes 
twoStep.description = Entrer votre code secret
twoStep.digit = Taper votre code à 6 chiffres
twoStep.account = Verifier mon compte

state.add = Ajout
state.detail = Détail
state.manage = Gestion
state.modify = Modification
state.more = Plus
state.overview = Vue d'ensemble
state.none = Aucun

product.entity = Produit
product.titleAdd = Ajouter un nouveau produit
product.titleSubAdd = Les commandes sont mises dans votre magasin
product.information = Informations du Produit
product.name = NOM
product.nameTitle = Nom Produit
product.barcode = CODE BARRE
product.description = DESCRIPTION (OPTIONEL)
product.quantity = QUANTITE
product.variant = VARIANTE
product.expDate = DATE D'EXPIRATION
product.supplier = FOURNISSEUR
product.price = PRIX
product.status = STATUT
product.pricing = TARIFS
product.basePrice = PRIX NORMAL
product.minPrice = PRIX MINIMUM
product.category = CATEGORIE
product.add = Ajouter Produit


category.add = Ajouter Categorie


lot.add = Ajouter Lot
lot.inStock = Dans les Stock
lot.addStock = Ajouter au Stock


btn.discard = Retour
btn.remove = Retirer
btn.add = Ajouter
btn.archive = Archiver
btn.save = Enregistrer