login.head = Bienvenu chez NeboTools
login.description = Veuillez vous connecter pour commencer a utiliser l'application

login.mailLabel = MAIL OU NOM D'UTILISATEUR
login.mailInput = Entrer votre mail ou nom d'utilisateur

login.passwordLabel = MOT DE PASSE
login.passwordInput = Entrer votre mot de passe

login.remember = Se rappeler de Moi

login.signIn = Se Connecter